ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_fk0";

ALTER TABLE "Order" DROP CONSTRAINT IF EXISTS "Order_fk0";

ALTER TABLE "Order"
  DROP CONSTRAINT IF EXISTS "Order_fk1";

ALTER TABLE "Order"
  DROP CONSTRAINT IF EXISTS "Order_fk2";

ALTER TABLE "Order"
  DROP CONSTRAINT IF EXISTS "Order_fk3";

ALTER TABLE "Room" DROP CONSTRAINT IF EXISTS "Room_fk0";

ALTER TABLE "Room" DROP CONSTRAINT IF EXISTS "Room_fk1";

ALTER TABLE "Room"
  DROP CONSTRAINT IF EXISTS "Room_fk2";

ALTER TABLE "Room_photo" DROP CONSTRAINT IF EXISTS "Room_photo_fk0";

ALTER TABLE "Room_photo" DROP CONSTRAINT IF EXISTS "Room_photo_fk1";

ALTER TABLE "Confirmation_order" DROP CONSTRAINT IF EXISTS "Confirmation_order_fk0";

ALTER TABLE "Confirmation_order" DROP CONSTRAINT IF EXISTS "Confirmation_order_fk1";

DROP TABLE IF EXISTS "User_role" CASCADE;

DROP TABLE IF EXISTS "User" CASCADE;

DROP TABLE IF EXISTS "Order" CASCADE;

DROP TABLE IF EXISTS "Room" CASCADE;

DROP TABLE IF EXISTS "Room_type" CASCADE;

DROP TABLE IF EXISTS "Room_bed" CASCADE;

DROP TABLE IF EXISTS "Room_photo" CASCADE;

DROP TABLE IF EXISTS "Confirmation_order" CASCADE;

DROP TABLE IF EXISTS "Order_status" CASCADE;

DROP TABLE IF EXISTS "Room_status" CASCADE;

